[package]
name = "apis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.10"
sha2 = "0.9"
num-bigint = "0.4.3"
rand = "0.8.4"
chrono = "0.4.26"
reqwest = { version = "0.11.4",features = ["blocking","json"]}
serde_json = "1.0.72"
serde = { version = "1.0", features = ["derive"] }
totp-rs = "5.0.2"
redis = "0.19.0"
mysql = "24.0.0"
rocket = "0.4.11"
sqlite = "0.31.0"
rocket_contrib = "0.4.11"
regex = "1.5"
urlencoding = "1.0"
tungstenite = "0.20.0"
